- SCCMPackager.ps1
New feature added. Use the -SingleRecipe function to only package a single recipe. You can tab-complete available recipes. This completes #19
> Single recipe mode

- Disabled/VLC.xml
Added a second deployment type for x64 and changed the URLS to download to https. Also added the /qn switch to the MSI install line.
> Added x64 VLC deployment. Changed URL to https and added a silent install switch.

- Disabled/Notepad++.xml
Added an x64 Deployment Type, and moved the x86 to Deployment Type 2.
> Update Notepad++ Recipe. Added x64 Deployment

- Disabled/GoogleHangoutsChat.xml
This .msi must be run as a user deployment.
> Google Hangouts Chat initial commit

- CMPackager.ps1
> Improve download logic in the prefetch script

- Disabled/DellCommandMonitor.xml
Also uses the Dell BIOS Provider icon.
> Add recipe for Dell Command Monitor

- Disabled/MicrosoftConfigMgrConsole.xml
Thought of a way to get the correct site server into the install arguments.
> Use correct site server in CM Console install

- Disabled/Scratch.xml
They changed the download filename slightly.
> Updated Scratch recipe

- CMPackager.ps1
Currently many errors are not visible in the log files, add the error and location to the log file.
Change is mostly indentation.
> Catch and log errors during recipe processing

- Disabled/Skype.xml
- ExtraFiles/Scripts/Get-RedirectedURL.ps1
Pre Download version check needs Get-RedirectedUrl Function:
https://github.com/WormieCorp/Wormies-AU-Helpers/blob/develop/Wormies-AU-Helpers/public/Get-RedirectedUrl.ps1
> Updated Skype Reciepe and added Get-RedirectedUrl.ps1 to ExtraFiles

- CMPackager.ps1
Updated CMPackager.ps1 to Support Folder Detection when $Version is used in folder name.
> Change CMPackager

- CMPackager.ps1
Replace $Version in Filename when  File Detection method is in use.
Second change helps when "" are used in Uninstall Command.
> Minor Changes

- CMPackager.prefs.template
- CMPackager.ps1
Add preference that allows for customization of the folder path with application name, publisher and version number. Addresses Issue #42
> Customization of the content folder path

- CMPackager.prefs.template
- CMPackager.ps1
- Recipes/Template.xml
Added a CSV split to support distribution to multiple DP groups. Also added DistributeToDPs into the template which looked to be missing.
> Update to allow for distribution to multiple DP groups 

- CMPackager.ps1
- Recipes/Template.xml
Added repair to the create and deploy functions. Addresses issue Repair Command #41
> Add Repair Application Ability

- Disabled/Git.xml
Also adds Install Behavior for git.exe, git-bash.exe, and git-cmd.exe.
> Allow git to use a setup inf from ExtraFiles

- Disabled/Wireshark.xml
The current link doesn't work anymore.
> fix Wireshark broken link

- Disabled/DellCommandMonitor.xml
> Dell monitor recipe update

- Disabled/FileZilla.xml
I had to add user agent values otherwise I keep getting `403 Forbidden` errors
> Add UserAget Values

- Disabled/FoxitPDFReader.xml
- Disabled/GoogleChrome.xml
- Disabled/Notepad++.xml
- Disabled/Watchguard Mobile VPN.xml
- Disabled/Watchguard Single Sign-On Client.xml
Google Chrome:
PrefetchScript failed with an exception indicating that $Download.Version does not exists. Removed the Prefetch Script
Notepad++ (x86):
Fixed PrefetchScript to same procedure as x64
Added:
Foxit Reader
Watchguard Mobile VPN with SSL
Watchguard Single Sign-On Client
> Fixed Google Chome & Notepad++ (x86), Added Foxit Reader, Watchguard VPN & SSO

- Disabled/AdobeReader.xml
Also added InstallBehavior and Supoersedence
> Updated recipe to fix detection method for Adobe Reader
