Disabled/WinSCP.xml

The 2nd Invoke-WebRequest is opening the default browser and attempting to auto-download the EXE.  Preventing redirects stops this undesired behavior, while still returning the necessary direct download URL.

Prevent auto-download by default browser

---

Recipes/_Application Requirements Template.xml

Instruction in ReadMe say to uncomment these lines if you want to package surface drivers.  On first run, I thought I was just creating the template app, but I accidentally downloaded a ton of Surface drivers I didn't need because these lines were un-commented by default and I didn't realize it.

These should be commented out by default according to ReadMe

---

CMPackager.ps1
Recipes/Template.xml

In our environment, applications are created in sub-folders under the root Applications node.
This pull request adds support for a `FolderPath` to be specified in the Recipe. If specified, the script will move the application to that location after it has been created.

Add support to create application a sub-folder

---

Disabled/Notepad++.xml
Recipes/Template.xml

Running the Notepad++ recipe results in the following error.
````
Invoke-WebRequest : The request was aborted: Could not create SSL/TLS secure channel.
At line:1 char:3
+ ((Invoke-WebRequest https://github.com/notepad-plus-plus/notepad-plus-plus/relea ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
eption
+ FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
````
Setting the `SecurityProtocol` to `Tls12` in the recipes `PrefetchScript` fixes the issue
````
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
````

Fixes for Notepad++ recipe

---

CMPackager.ps1
Recipes/Template.xml

New Feature: Application Supersedence
- Enable Supersedence in an application's Recipe to automatically supersede the previously packaged application with the newly packaged version.
NOTE: Certain errors could result in a broken package (download URL change, etc.), in these cases, supersedence may cause issues! Ensure you understand the repercussions of supersedence before enabling it for an application!
Resolves #20

New Feature: Application Supersedence

---

CMPackager.ps1
Disabled/JetBrains-Toolbox.xml

Allows a download precheck to prevent downloading applications if the version can be determined in the prefetchscript.
To enable the download precheck for a recipe, simply assign the detected version to the variable $Download.Version in the <prefetchscript> for each download. if a version is detected after the prefetch script runs, a check will run if the app already exists in ConfigMgr, download of the app will only occur if the app is not found in ConfigMgr. Completes #24

Enable Download PreCheck feature

---

Disabled/MozillaFirefoxESR.xml

The MSI version has a trailing ".0" which means we can't necessarily compare that version against the download version. Need to use the version in the URL instead for consistency.

Add version prefetch to Firefox recipe

---

Disabled/MozillaFirefoxESR.xml

Was referring to match group instead of the value of the matched text in the prefetch block. This change fixes that. Sorry.

Firefox version pre-check bug fix

---

CMPackager.ps1

Ensures the psdrive is available if it's not automatically connected

Add CM PSDrive in script scope

---

CMPackager.ps1

- Add an alias `-Recipe` to `-SingleRecipe`
- Allow specifying more than one recipe to run at a time, eg `.\CMPackager.ps1 -Verbose -Recipe Git.xml,PowerShell.xml` will run Git and PowerShell, but not other things in the Recipes folder.

Allow running multiple specific recipes & add alias to '-Recipe`

---

Disabled/Git.xml
Disabled/PowerShell.xml

GitHub releases have the version in the URL so the same sort of thing will work for lots of recipes.

Check version of Git & PowerShell without downloading

---

CMPackager.ps1
Disabled/MicrosoftConfigMgrConsole.xml

The CM Console installer's versions are not changed for hotfixes, even if the installed Console's version changes, so use the extracted contents of the installer for version checking.
Performing an administrative install of the msi is a fairly horrible way to achieve this but 7za can't expand msis usefully (7z.exe can).

Use CM Console msi's file table for version check

---

CMPackager.prefs.template
CMPackager.ps1

Add preference entry for PS module location outside of console install. Defaults to SMS_ADMIN_UI_PATH if not defined. This allows for flexibility of the repository without having to install the console.

Add preference for custom PS module path

---

CMPackager.ps1
Recipes/Template.xml

Function dynamically builds out New-CMApplication command to optionally use all available parameters.
- Name is the only required field
- Icon, publisher, description, user documentation is now optional, previously required
- Split out user documentation url and optional reference
- Split out software center description and admin description
- Add optional keywords, owner, support contact, privacy url, link text, display superseded app, featured app,
- Sets administrative and user categories. Creates them if not found.
Note: When adding Owner and Support Contacts script warns of deprecation, but it's not documented on MS docs.

Update Invoke-ApplicationCreation function with all application fields

---

Disabled/MicrosoftPowerToys.xml

Project switched from releasing an MSI to an exe containing an MSI, quick & dirty fix by extracting the MSI.

Fix PowerToys recipe

---

CMPackager.ps1

`-IconLocationFile $null` causes `New-CMApplication` to error at parameter binding

Don't specify -IconLocationFile if icon inaccessible

---

CMPackager.ps1

The original goal was allow `-InstallCommand` to be set with all MSI detection types, but after that I realised it could be handled with the other `stDepType*` variables, like `-UninstallCommand` etc.

Don't special-case InstallCommand handling

---

CMPackager.ps1

Causes a `ParameterBindingException` when calling `New-CMApplication`, possibly depending on the date or date format.

Don't put quotes around get-date call

---

Disabled/AzureDataStudio.xml
Disabled/Git.xml
Disabled/MozillaFirefox.xml
Disabled/PowerShell.xml
Disabled/VisualStudioCode.xml
Disabled/vcxsrv.xml

- Script installation types don't do string expansion on UninstallCmd, so the backticks to escape quotes get removed.
- UninstallOption NoneRequired set where appropriate
- Some InstallBehaviours set

Uninstaller fixes & uninstalloptions for several recipes

---

CMPackager.ps1

Adding two lines to allow for dynamic versioning in the registry key path and the file detection paths when the program installations add those for each version. This is similar to how the ExpectedValue is handle.

Update CMPackager.ps1 to Allow for Dynamic Versioning in Detection Paths

---

.gitignore
CMPackager.ps1
Disabled/_RecipeSchema.xsd

This is a proposed fix for #113 
Adds a function to cleanup superseded applications as part of the run.  The recipe schema changes just a little bit - a line to turn it on, and a line for how many to keep.

Adding superseded application cleanup

---

CMPackager.ps1

- Parameters added to specify alternate preference file and recipe path
- Added site code to email subject/body
I've been using this in my environment were we have several teams working on a couple different MECM installs. This allows us to use the same repository but specify different preferences.
Will also help with #81

add options for alternate perference and recipe path

---

Disabled/Notepad++.xml

Github is now dynamically rendering the download link in the front end of the website, and is not visible in Sources.  Because invoke-webrequest cannot render the page in IE's absence, this now looks for the "current version" link directly at notepad-plus-plus.org, then grabs the first .x64.exe file from the subsequent page, and then goes directly to the GitHub download.

Update Notepad++ Recipe

---

CMPackager.ps1
Recipes/Template.xml

Removes the hardcoded "available" deployment purpose and instead uses the value specified in the new "Purpose" option in recipes. New-CMApplicationDeployment defaults to "available" if -DeployPurpose is not specified.
Fixed the SingleRecipe dynamic parameter so it won’t complain about an unresolved part when not explicitly specifying -RecipePath. Also amended the parameter logic to only consider xml files and fall back to the standard recipe directory if called from the CMpackager directory. 
Lastly a minor fix to the cast of RecipePath parameter from file to directory. 
These should help address #128 , #134 and #138

Add recipe deployment option available/required
